AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an EC2 web server with a security group that enables SSH, HTTP connection.
 
Resources:
  Myserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02e136e904f3da870
      InstanceType: t2.micro
      KeyName: firstkey.pem
      SecurityGroups:
        - ilkSecGrp
      Tags:
        - Key: Name 
          Value: Web Server of StackName
      UserData: |
        #!/bin/bash
        sudo yum update -y
        sudo yum install httpd -y
        sudo chmod -R 777 /var/www/html
        cd /var/www/html
        wget 
        sudo systemctl start httpd
        sudo systemctl enable httpd