AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an EC2 with security group that enables SSH, HTTP connection with elasticIP.

Resources:
  MyInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02e136e904f3da870
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref SSHSG
        - !Ref ServerSG
  
  MyIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance2
  
  SSHSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: slack icin olusturuldu # Required
      GroupName: ilkscgrp
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: slack icin olusturuldu # Required
      GroupName: IKIscgrp
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 192.168.1.1/32